### ISSUE TITLE
Font Customizer Support

### ISSUE THREAD

**Issue by mrpritchett** [LiftUX/uptown-style-theme#2]

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rBlEeVxD&#x2F;18-ascension-business-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Ascension (Business Theme)</a>
